## 创建 ndarray

- 从Python中的列表、元组等类型创建ndarray数组
- 使用NumPy中函数创建ndarray数组，如：arange, ones, zeros 等
- 从字节流（raw bytes）中创建ndarray数组
- 从文件中读取特定格式，创建ndarray数组

In [1]:
import numpy as np

### list or tuple

In [2]:
np.array([0, 1, 2, 3]) # list

array([0, 1, 2, 3])

In [3]:
np.array((0, 1, 2, 3)) # tuple

array([0, 1, 2, 3])

In [4]:
np.array([[1,2], [9,8], (0.1, 0.2)]) # 混合

array([[1. , 2. ],
       [9. , 8. ],
       [0.1, 0.2]])

### NumPy 函数

如：arange, ones, zeros 等

- `np.arange(n)` 类似range()函数，返回ndarray类型，元素从0到n‐1
- `np.ones(shape)` 根据shape生成一个全1数组，shape是元组类型
- `np.zeros(shape)` 根据shape生成一个全0数组，shape是元组类型
- `np.full(shape,val)` 根据shape生成一个数组，每个元素值都是val
- `np.eye(n)` 创建一个正方的n*n单位矩阵，对角线为1，其余为0

In [5]:
np.array(10)

array(10)

In [6]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.zeros((5,3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
x = np.full((2,3,4), 9)
x

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [10]:
x.shape

(2, 3, 4)

- `np.linspace()` 根据起止数据等间距地填充数据，形成数组
- `np.concatenate()` 将两个或多个数组合并成一个新的数组

In [11]:
a = np.linspace(1, 10, 4)
a

array([ 1.,  4.,  7., 10.])

In [12]:
b = np.linspace(1, 10, 4, endpoint=False)
b

array([1.  , 3.25, 5.5 , 7.75])

In [13]:
np.concatenate((a, b))

array([ 1.  ,  4.  ,  7.  , 10.  ,  1.  ,  3.25,  5.5 ,  7.75])