## 索引&切片

In [1]:
import numpy as np

### 一维数组

In [3]:
a = np.array([9,8,7,6,5])
a

array([9, 8, 7, 6, 5])

In [4]:
a[2] # index

7

In [5]:
a[1:4:2] # slice 返回ndarray对象

array([8, 6])

### 多维数组

In [6]:
a = np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

#### index

In [7]:
a[1,2,3]

23

In [8]:
a[-1,-2,-3]

17

#### slice

In [9]:
a[:, 1, -3]

array([ 5, 17])

In [10]:
a[:, 1:3, :]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [11]:
a[:, 1:3, ::2]

array([[[ 4,  6],
        [ 8, 10]],

       [[16, 18],
        [20, 22]]])