# NumPy 随机数 函数

`np.random` 下面的各种函数

In [1]:
import numpy as np

## 按值产生数or数组

形状不写，默认一个数

函数 | 说明
-- | --
`rand(d0,d1,..,dn)` | 根据d0‐dn创建随机数数组，浮点数，[0,1)，均匀分布
`randn(d0,d1,..,dn)` | 根据d0‐dn创建随机数数组，标准正态分布
`randint(low,high[,shape])` | 根据shape创建随机整数或整数数组，范围是[low, high)
`seed(s)` | 随机数种子，s是给定的种子值

In [2]:
np.random.rand()

0.1312641172921194

In [3]:
np.random.rand(2,3,4) # 0-1 随机分布

array([[[0.92856281, 0.64799735, 0.93291654, 0.93831433],
        [0.23915473, 0.53307949, 0.15276633, 0.76518631],
        [0.08136714, 0.4548479 , 0.5178648 , 0.54593483]],

       [[0.48477015, 0.22405182, 0.53264063, 0.60872525],
        [0.32789379, 0.72134315, 0.16904562, 0.5565849 ],
        [0.71198952, 0.82783959, 0.40190552, 0.41283458]]])

In [4]:
np.random.randn(2,3,4) # 正态分布

array([[[ 0.03300644,  1.10273523,  1.41165403, -1.39137744],
        [-0.26075574, -0.32079219, -0.37912608,  0.63283365],
        [-0.52390377,  1.75816767, -0.04090268,  1.19797867]],

       [[ 1.42410391,  0.58110727,  0.55377343, -0.43143277],
        [ 1.11889378,  0.94288128,  1.99847136,  0.13261688],
        [-0.33405298, -1.79635228, -1.64510687, -0.09166618]]])

In [5]:
np.random.randint(0, 100, (2, 3, 4))

array([[[80, 78, 12, 44],
        [71, 48, 89, 31],
        [69, 61, 23, 54]],

       [[11, 93, 62, 94],
        [75, 80, 38, 96],
        [49, 14, 76, 41]]])

## 打乱数组，抽取元素

函数 | 说明
-- | --
`shuffle(a)` | 根据数组a的第1轴进行随排列，改变数组x
`permutation(a)` | 根据数组a的第1轴产生一个新的乱序数组，不改变数组x
`choice(a,[size,replace,p])` | 从一维数组a中以概率p抽取元素，形成size形状新数组 replace表示是否可以重用元素，默认为True，使用重复元素

In [6]:
a = np.random.randint(0, 100, (3, 4))
a

array([[29,  2, 69, 97],
       [18, 14, 71, 64],
       [15, 48, 26, 24]])

In [7]:
np.random.shuffle(a) # 将 a 乱序
a

array([[18, 14, 71, 64],
       [15, 48, 26, 24],
       [29,  2, 69, 97]])

In [8]:
np.random.permutation(a) # 生成新的数组

array([[29,  2, 69, 97],
       [15, 48, 26, 24],
       [18, 14, 71, 64]])

In [9]:
b = a.flatten()
b

array([18, 14, 71, 64, 15, 48, 26, 24, 29,  2, 69, 97])

In [10]:
np.random.choice(b)  # 传入的必须是一维数组

26

In [11]:
np.random.choice(b, (2, 3)) # 形成一个二维数组

array([[97, 15, 14],
       [64, 14, 24]])

In [12]:
np.random.choice(b, (2, 3), False) # 不重复

array([[29, 15, 64],
       [97, 48,  2]])

In [13]:
np.random.choice(b, (2,3), p=b/np.sum(b)) # 指定每个被选择的概率
# 在这里是数字越大概率越大 因为是数组除以 总和

array([[69, 48, 97],
       [71, 48, 97]])

## 生成对应分布的数组

函数 | 说明
-- | --
`uniform(low,high,size)` | 产生具有均匀分布的数组,low起始值,high结束值
`normal(loc,scale,size)` | 产生具有正态分布的数组,loc均值,scale标准差
`poisson(lam,size)` | 产生具有泊松分布的数组,lam随机事件发生率

In [14]:
np.random.uniform(0, 100, (2,3,4))

array([[[35.44602136,  5.41839997, 66.97149633, 10.65885807],
        [98.82785763, 34.13082339, 90.40819292, 90.71208261],
        [ 0.2617123 , 59.17673886, 66.02351759, 91.17682886]],

       [[77.28304336, 76.93510112, 37.48269848, 27.96858523],
        [70.61107813, 45.87354717, 15.64577411, 55.8606734 ],
        [11.31277426, 70.47207059, 36.4295098 , 54.79517831]]])

In [15]:
np.random.normal(10, 2, (2,3,4))	

array([[[ 9.77985378, 10.08310559,  4.49743259,  7.868118  ],
        [11.22870751, 14.02869491,  8.96914521, 10.54932666],
        [ 8.57624995, 10.25308174,  8.80901539,  9.78305069]],

       [[12.38870619,  9.10567538,  8.67781011, 11.01497098],
        [ 9.91536   ,  9.48600717,  7.00410281, 11.58981625],
        [ 7.58137771, 11.44612862, 13.44918118, 11.00392573]]])

In [16]:
np.random.poisson(0.9, (3,4))

array([[1, 0, 2, 1],
       [2, 5, 0, 0],
       [0, 2, 1, 1]])