# NumPy 统计类函数

直接提供：`np.*`

函数 | 说明 (axis整数或元组)
-- | --
`sum(a, axis=None)` | 根据给定轴axis，计算数组a相关元素之和
`mean(a, axis=None)` | 根据给定轴axis，计算数组a相关元素的期望
`average(a,axis=None,weights=None)` | 根据给定轴axis，计算数组a相关元素的加权平均值
`std(a, axis=None)` | 根据给定轴axis，计算数组a相关元素的标准差
`var(a, axis=None)` | 根据给定轴axis，计算数组a相关元素的方差

- axis=0 为第一维度
- axis=1 为第二维度
- axis=(0,1) 为一、二维形成的数组？

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
np.sum(a)

105

In [4]:
np.sum(a, 1) # 第二个维度？
# sum(a, axis, dtype, out, keepdims, initial, where) # 完整参数

array([10, 35, 60])

In [5]:
np.mean(a, 0) # 第一个维度

array([5., 6., 7., 8., 9.])

In [6]:
np.average(a, 0, weights=[10,5,1]) # weights 加权平均数
# average(a, axis, weights, returned)

array([2.1875, 3.1875, 4.1875, 5.1875, 6.1875])

In [7]:
np.average(a, 1, [3,2,3,4,1]) # 测试第二个维度

array([ 1.84615385,  6.84615385, 11.84615385])

In [8]:
np.std(a) # 标准差 standard deviation

4.320493798938574

In [9]:
np.var(a, 1) # 方差 variance

array([2., 2., 2.])

函数 | 说明
-- | --
`min(a) max(a)` | 计算数组a中元素的最小值、最大值
`argmin(a) argmax(a)` | 计算数组a中元素最小值、最大值的降一维后下标
`unravel_index(index, shape)` | 根据shape将一维下标index转换成多维下标
`ptp(a)` | 计算数组a中元素最大值与最小值的差
`median(a)` | 计算数组a中元素的中位数（中值）

第二个参数也是 axis

In [10]:
ar = np.random.randint(0, 100, (3,5))
ar

array([[ 4, 15, 82, 69, 12],
       [77, 68,  3, 11, 66],
       [69, 53, 44, 22, 23]])

In [11]:
np.min(ar)

3

In [12]:
np.max(ar, 1)

array([82, 77, 69])

In [13]:
np.argmax(ar)

2

In [14]:
np.argmin(ar)

7

In [15]:
np.unravel_index(np.argmin(ar), ar.shape)

(1, 2)

In [16]:
np.ptp(ar)

79

In [17]:
np.median(ar, 0) # 中位数

array([69., 53., 44., 22., 23.])

## 梯度函数

`np.gradient(f)` 计算数组f中元素的梯度，当f为多维时，返回每个维度梯度

梯度：连续值之间的变化率，即斜率，**在多媒体运算中发现边缘**
- XY坐标轴连续三个X坐标对应的Y轴值：a, b, c，其中，b的梯度是： (c‐a)/2
- 只有一侧，使用自身的值 除以 1

完整参数：`(f, *varargs, axis=None, edge_order=1)`

In [18]:
oda = np.random.randint(0, 20, 5)
oda

array([ 1,  8, 15, 13, 18])

In [19]:
np.gradient(oda) # 最后一个5 = 18 - 13 

array([7. , 7. , 2.5, 1.5, 5. ])

In [20]:
bda = np.random.randint(0, 20, (3, 4))
bda

array([[ 1,  1, 11, 12],
       [ 8,  4,  9, 19],
       [17, 15, 15,  0]])

In [21]:
np.gradient(bda) # 第一个数组是最外层维度 纵列算梯度

[array([[  7.,   3.,  -2.,   7.],
        [  8.,   7.,   2.,  -6.],
        [  9.,  11.,   6., -19.]]),
 array([[  0. ,   5. ,   5.5,   1. ],
        [ -4. ,   0.5,   7.5,  10. ],
        [ -2. ,  -1. ,  -7.5, -15. ]])]