### 维度变换

一般无返回值，会修改原数组

- `.reshape(shape)` 不改变数组元素，返回一个shape形状的数组，原数组不变
- `.resize(shape)` 与`.reshape()`功能一致，但修改原数组
- `.swapaxes(ax1,ax2)` 将数组n个维度中两个维度进行调换
- `.flatten()` 对数组进行降维，返回折叠后的一维数组，原数组不变
- `.astype(np.类型)` 返回新类型的数组

In [1]:
import numpy as np

In [2]:
a = np.ones((2,3,4), dtype=np.int32)
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [3]:
a.reshape((3,8)) # 总体个数不变

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [4]:
a.resize((3,8)) # resize 没返回值，所以修改了a
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [5]:
a.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [7]:
a.astype(np.float)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

`.tolist()`

In [8]:
a.tolist()

[[1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]