# 数组运算

## 标量

数组与标量计算为：数组中的每个元素与该标量进行计算

### 计算数组与元素平均值的商

In [16]:
import numpy as np
a = np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [17]:
a.mean()

11.5

In [18]:
x = a / a.mean()
x

array([[[0.        , 0.08695652, 0.17391304, 0.26086957],
        [0.34782609, 0.43478261, 0.52173913, 0.60869565],
        [0.69565217, 0.7826087 , 0.86956522, 0.95652174]],

       [[1.04347826, 1.13043478, 1.2173913 , 1.30434783],
        [1.39130435, 1.47826087, 1.56521739, 1.65217391],
        [1.73913043, 1.82608696, 1.91304348, 2.        ]]])

一元函数 | 说明
-- | --
`np.rint(x)`  | 计算数组各元素的四舍五入值
`np.modf(x)`  | 将数组各元素的小数和整数部分以两个独立数组形式返回
`np.cos(x)` `np.cosh(x)` |
`np.sin(x)` `np.sinh(x)` | 计算数组各元素的普通型和双曲型三角函数
`np.tan(x)` `np.tanh(x)` |
`np.exp(x)` | 计算数组各元素的指数值
`np.sign(x)` | 计算数组各元素的符号值，1(+), 0, ‐1(‐)

In [19]:
np.square(x)

array([[[0.        , 0.00756144, 0.03024575, 0.06805293],
        [0.12098299, 0.18903592, 0.27221172, 0.3705104 ],
        [0.48393195, 0.61247637, 0.75614367, 0.91493384]],

       [[1.08884688, 1.2778828 , 1.48204159, 1.70132325],
        [1.93572779, 2.1852552 , 2.44990548, 2.72967864],
        [3.02457467, 3.33459357, 3.65973535, 4.        ]]])

In [20]:
np.modf(x)

(array([[[0.        , 0.08695652, 0.17391304, 0.26086957],
         [0.34782609, 0.43478261, 0.52173913, 0.60869565],
         [0.69565217, 0.7826087 , 0.86956522, 0.95652174]],
 
        [[0.04347826, 0.13043478, 0.2173913 , 0.30434783],
         [0.39130435, 0.47826087, 0.56521739, 0.65217391],
         [0.73913043, 0.82608696, 0.91304348, 0.        ]]]),
 array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 2.]]]))

二元 | 说明
--|--
`+ - * / **` | 两个数组各元素进行对应运算
`np.maximum(x,y) np.fmax()` | 元素级的最大值计算
`np.minimum(x,y) np.fmin()` | 元素级的最小值计算
`np.mod(x,y)` | 元素级的模运算
`np.copysign(x,y)` | 将数组y中各元素值的符号赋值给数组x对应元素
`> < >= <= == !=` | 算术比较，产生布尔型数组

In [22]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
b = np.arange(-12, 12, 2).reshape((4,3))
b

array([[-12, -10,  -8],
       [ -6,  -4,  -2],
       [  0,   2,   4],
       [  6,   8,  10]])